
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: ecommerce_development






test:
  <<: *default
  database: ecommerce_test
production:
  primary: &primary_production
    <<: *default
    database: ecommerce_production
    username: ecommerce
    password: <%= ENV["ECOMMERCE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: ecommerce_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ecommerce_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ecommerce_production_cable
    migrations_paths: db/cable_migrate
